swagger: '2.0'
info:
    version: '1.0'
    title: Author's Haven.
    description: 'A Social platform for the creative at heart.'

schemes:
  - https
host: forsetti-ah-backend-staging.herokuapp.com
basePath: '/api/v1'
paths:
  /auth/signup:
    post:
      tags:
      - "Users"
      summary: "Register a new user on the application"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New user that needs to be created on the application"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: "User registered successfully"
          example:
            status: 201
            message: "User registered successfully"
            data:
              - token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmY4Y2Y4LWIwNzQtNDE1ZC04MDYxLWVjZDBkMzgzZjQ0NiIsImlhdCI6MTU1NDEwODc4MSwiZXhwIjoxNTU2NzAwNzgxfQ.e6K_0U36u3b16JFsAwcO1fJA0onVSKa1KRGQVFEhm3g"
                user:
                  firstname: "Zokky 2"
                  lastname: "Umeilechukwu"
                  email: "o.yes@gmail.com"
        503:
          description: "Some error occurred"
  /auth/signin:
    post:
      tags:
      - "Users"
      summary: "Sign in an existing user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "An existing user that returns to be signed in"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: "Signed in successfully"
          example:
            status: 201
            message: "Signed in successfully"
            data:
              - user:
                  email: "o.yes@gmail.com"
                  password: "password"
        400:
          description: "Sign in with invalid credentials"
          example:
            status: 400
            message: "Invalid Credentials"
            data:
              - token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmY4Y2Y4LWIwNzQtNDE1ZC04MDYxLWVjZDBkMzgzZjQ0NiIsImlhdCI6MTU1NDEwODc4MSwiZXhwIjoxNTU2NzAwNzgxfQ.e6K_0U36u3b16JFsAwcO1fJA0onVSKa1KRGQVFEhm3g"
                user:
                  email: "o.yes@gmail.com"
                  password: "password"
        503:
          description: "Some error occurred. Please try again"
definitions:
  User:
    type: "object"
    properties:
      firstname:
        type: "string"
      lastname:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"

tags:
  - name: 'Authentication'

paths:
  /auth/facebook:
    description: 'This endpoint enables a user sign in with facebook'
    tags:
      - Authentication
    responses:
      200:
        description: 'Auto generated using Swagger Inspector'

  /auth/twitter:
    description: 'This endpoint enables a user sign in with twitter'
    tags:
      - Authentication
    responses:
      200:
        description: 'Auto generated using Swagger Inspector'

  /auth/google:
    description: 'This endpoint enables a user sign in with google'
    tags:
      - Authentication
    responses:
      200:
        description: 'Auto generated using Swagger Inspector'
